# config/default.yaml
# Default configuration for 3D-VAEGAN models

# Model Parameters for testing
n_epochs: 200
batch_size: 10
g_lr: 0.0025
e_lr: 0.0001
d_lr: 0.001
beta: [0.5, 0.5]
d_thresh: 0.8
z_size: 200
z_dis: "norm"
bias: false
leak_value: 0.2
cube_len: 32
image_size: 224
soft_label: true
lrsh: true

# Directory Parameters
output_dir: "../output"
input_dir: "../input"
pickle_dir: "pickle"
log_dir: "log"
image_dir: "image"
data_dir: "chair"

# Step Parameters
pickle_step: 10
log_step: 1
image_save_step: 10

# Other Parameters
alg_type: "3DVAEGAN"
#combine_type: "mean"
#num_views: 12
model_name: "Singleview"
use_tensorboard: true
mode: "train"

# Object category
obj: "chair"


